In [51]:
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt
from sklearn.metrics import confusion_matrix,classification_report
import seaborn as sns
from imblearn.under_sampling import RandomUnderSampler
from sklearn.metrics import roc_auc_score
from sklearn import preprocessing
import joblib

In [52]:
df = pd.read_csv("Encoded Data Combined/Final Combined Data/new_train_data_akeshala_nipun_samal.csv", encoding='latin-1')
df_validation = pd.read_csv("Encoded Data Combined/Final Combined Data/new_validation_data_akeshala_nipun_samal.csv", encoding='latin-1')
x_train = df.drop(columns=["Reservation_Status","Reservation-id"]).iloc[:,2:]
y_train = df.iloc[:,22:23]
x_validation = df_validation.drop(columns=["Reservation_Status","Reservation-id"]).iloc[:,2:]
y_validation = df_validation.iloc[:,22:23]

In [53]:
#under sample
rus = RandomUnderSampler(random_state = 21)
x_train, y_train = rus.fit_sample(x_train, y_train)

In [54]:
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

sc = StandardScaler()

x_train = sc.fit_transform(x_train)
x_validation = sc.transform(x_validation)

In [55]:
from sklearn.ensemble import RandomForestClassifier

classifier = RandomForestClassifier(random_state = 23)
classifier.fit(x_train, y_train.values.ravel())

joblib.dump(classifier, 'randomforest_a0.37_f0.33.pkl') 

#classifier = joblib.load('randomforestmodel.pkl')

y_pred = classifier.predict(x_validation)
print(f"Accuracy = {classifier.score(x_validation,y_validation.values.ravel())}")

Accuracy = 0.3539468897781011


In [56]:
cm = confusion_matrix(y_validation,y_pred)
print(cm)
print(classification_report(y_validation, y_pred))

[[631 429 550]
 [272 202 267]
 [149 109 140]]
              precision    recall  f1-score   support

           0       0.60      0.39      0.47      1610
           1       0.27      0.27      0.27       741
           2       0.15      0.35      0.21       398

    accuracy                           0.35      2749
   macro avg       0.34      0.34      0.32      2749
weighted avg       0.45      0.35      0.38      2749



In [57]:
from sklearn.ensemble import AdaBoostClassifier

classifier = AdaBoostClassifier(random_state = 21)
classifier.fit(x_train, y_train.values.ravel())
y_pred = classifier.predict(x_validation)

print(f"Accuracy = {classifier.score(x_validation,y_validation.values.ravel())}")

Accuracy = 0.35467442706438707


In [58]:
cm = confusion_matrix(y_validation,y_pred)
print(cm)
print(classification_report(y_validation, y_pred))

[[677 292 641]
 [279 141 321]
 [155  86 157]]
              precision    recall  f1-score   support

           0       0.61      0.42      0.50      1610
           1       0.27      0.19      0.22       741
           2       0.14      0.39      0.21       398

    accuracy                           0.35      2749
   macro avg       0.34      0.34      0.31      2749
weighted avg       0.45      0.35      0.38      2749



In [59]:
from sklearn.ensemble import GradientBoostingClassifier
classifier = GradientBoostingClassifier(learning_rate=0.005,n_estimators=1500,random_state=21,max_depth=7)
classifier.fit(x_train, y_train.values.ravel())
joblib.dump(classifier, 'gradientboostmodel.pkl') 

classifier = joblib.load('gradientboostmodel.pkl')
y_pred = classifier.predict(x_validation)


print(f"Accuracy = {classifier.score(x_validation,y_validation.values.ravel())}")

Accuracy = 0.3463077482720989


In [60]:
cm = confusion_matrix(y_validation,y_pred)
print(cm)
print(classification_report(y_validation, y_pred))

[[575 434 601]
 [263 221 257]
 [145  97 156]]
              precision    recall  f1-score   support

           0       0.58      0.36      0.44      1610
           1       0.29      0.30      0.30       741
           2       0.15      0.39      0.22       398

    accuracy                           0.35      2749
   macro avg       0.34      0.35      0.32      2749
weighted avg       0.44      0.35      0.37      2749

