In [105]:
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt
from sklearn.metrics import confusion_matrix,classification_report
import seaborn as sns
from imblearn.under_sampling import RandomUnderSampler
from sklearn.metrics import roc_auc_score
from sklearn import preprocessing
import joblib

In [193]:
df = pd.read_csv("Encoded Data Combined/Final Combined Data/new_train_data_akeshala_nipun_samal.csv", encoding='latin-1')
df_validation = pd.read_csv("Encoded Data Combined/Final Combined Data/new_validation_data_akeshala_nipun_samal.csv", encoding='latin-1')
x_train = df.drop(columns=["Reservation_Status","Reservation-id","Previous_Cancellations"]).iloc[:,1:]
y_train = df.iloc[:,21:22]
x_validation = df_validation.drop(columns=["Reservation_Status","Reservation-id","Previous_Cancellations"]).iloc[:,1:]
y_validation = df_validation.iloc[:,21:22]

In [184]:
#combining childern and babies
x_train['Children']=x_train['Children']+x_train['Babies']
x_train = x_train.drop(columns=['Babies'])
x_validation['Children']=x_validation['Children']+x_validation['Babies']
x_validation = x_validation.drop(columns=['Babies'])

In [194]:
#under sample
rus = RandomUnderSampler(random_state = 21)
x_train, y_train = rus.fit_sample(x_train, y_train)

In [195]:
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

sc = StandardScaler()

x_train = sc.fit_transform(x_train)
x_validation = sc.transform(x_validation)

In [196]:
from sklearn.ensemble import RandomForestClassifier

classifier = RandomForestClassifier(random_state = 23)
classifier.fit(x_train, y_train.values.ravel())

#joblib.dump(classifier, 'randomforestmodel.pkl') 

#classifier = joblib.load('randomforestmodel.pkl')

y_pred = classifier.predict(x_validation)
print(f"Accuracy = {classifier.score(x_validation,y_validation.values.ravel())}")

Accuracy = 0.364496180429247


In [197]:
cm = confusion_matrix(y_validation,y_pred)
print(cm)
print(classification_report(y_validation, y_pred))

[[200 247 294]
 [117 126 155]
 [425 509 676]]
              precision    recall  f1-score   support

           0       0.27      0.27      0.27       741
           1       0.14      0.32      0.20       398
           2       0.60      0.42      0.49      1610

    accuracy                           0.36      2749
   macro avg       0.34      0.34      0.32      2749
weighted avg       0.45      0.36      0.39      2749



In [198]:
from sklearn.ensemble import AdaBoostClassifier

classifier = AdaBoostClassifier(random_state = 21)
classifier.fit(x_train, y_train.values.ravel())
y_pred = classifier.predict(x_validation)

print(f"Accuracy = {classifier.score(x_validation,y_validation.values.ravel())}")

Accuracy = 0.3917788286649691


In [199]:
cm = confusion_matrix(y_validation,y_pred)
print(cm)
print(classification_report(y_validation, y_pred))

[[119 263 359]
 [ 72 132 194]
 [257 527 826]]
              precision    recall  f1-score   support

           0       0.27      0.16      0.20       741
           1       0.14      0.33      0.20       398
           2       0.60      0.51      0.55      1610

    accuracy                           0.39      2749
   macro avg       0.34      0.34      0.32      2749
weighted avg       0.44      0.39      0.41      2749



In [200]:
from sklearn.ensemble import GradientBoostingClassifier
classifier = GradientBoostingClassifier(learning_rate=0.005,n_estimators=1500,random_state=21,max_depth=7,min_samples_split=1600,min_samples_leaf=30,max_features=2,subsample=1)
classifier.fit(x_train, y_train.values.ravel())
y_pred = classifier.predict(x_validation)

print(f"Accuracy = {classifier.score(x_validation,y_validation.values.ravel())}")

Accuracy = 0.4128774099672608


In [201]:
cm = confusion_matrix(y_validation,y_pred)
print(cm)
print(classification_report(y_validation, y_pred))

[[113 225 403]
 [ 75 106 217]
 [250 444 916]]
              precision    recall  f1-score   support

           0       0.26      0.15      0.19       741
           1       0.14      0.27      0.18       398
           2       0.60      0.57      0.58      1610

    accuracy                           0.41      2749
   macro avg       0.33      0.33      0.32      2749
weighted avg       0.44      0.41      0.42      2749

